name: Clear CloudFlare cache
on: [deployment]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Call CloudFlare API
      env:
        CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
      run: |
        [[ -n "$CLOUDFLARE_TOKEN" ]] || \
          ( echo "Error: Must set CLOUDFLARE_TOKEN secret"; exit 1 )
        curl -sS -X POST \
          "https://api.cloudflare.com/client/v4/zones/<ZONE_ID>/purge_cache" \
          -H "Authorization: Bearer $CLOUDFLARE_TOKEN" \
          -H "Content-Type: application/json" \
          --data '{"purge_everything": true}'
