# Site
lang: "vi"
future: true
name: "Anh hàng xóm Blogs"
title: "Anh hàng xóm"
description: "Welcome to Xóm nghiện ngập!<br />(－ω－) zzZ<br /> Nghiện công việc, Nghiện du lịch và Sức khỏe!"
logo: 'assets/images/logo.webp'
favicon: 'assets/images/logo.webp'
url: "https://nhamngoctuananh.github.io/"
#baseurl: /
encoding: UTF-8
google_analytics: 'UA-192636660-1'
timezone: Asia/Ho_Chi_Minh
include: ["_pages"]
permalink: /:title/
email: tuananhtlu9366@gmail.com

# Authors
authors:
  sal:
    name: Nhâm Ngọc Tuấn Anh
    display_name: Anh Hàng Xóm
    avatar: 'assets/images/avatar-sal.webp'
    email: tuananhtlu9366@gmail.com
    web: https://anhhangxom.xyz/
    twitter: https://twitter.com/wowthemesnet
    facebook: https://www.facebook.com/nntatlu
    description: "Xin chào, tôi là lập trình viên backend. Với đam mê chụp ảnh, lập trình và đi chơi. Tôi xây dựng blog với mục đích là chia sẻ kinh nghiêm coder, cuộc sống thường ngày và sức khỏe cho developer ."
  john:
    name: Nhâm Ngọc Tần
    display_name: Nhâm Ngọc Tần
    avatar: 'assets/images/tan.jpg'
    facebook: https://www.facebook.com/tan.nhamngoc
    description: "Quan trọng là thần thái!"
  minh:
    name: Phạm Nhật Minh
    display_name: Quả táo tàu
    avatar: 'assets/images/tao-tau.webp'
    facebook: https://www.facebook.com/minhtron.6998
    description: "Đơn giản là Minh, nhưng Minh không đơn giản"


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-minifier
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
  - jekyll-toc

toc:
  min_level: 1
  max_level: 6
  ordered_list: false
  no_toc_section_class: no_toc_section
  list_id: toc
  list_class: section-nav
  sublist_class: ''
  item_class: toc-entry
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "enabled"
adsense-data-ad-client: "ca-pub-8920573839255504"
adsense-data-ad-slot: "8350440762"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

############################################################
# Site configuration for the WebP Generator Plugin
# The values here represent the defaults if nothing is set
webp:
  enabled: true

  # The quality of the webp conversion 0 to 100 (where 100 is least lossy)
  quality: 100

  # List of directories containing images to optimize, nested directories will only be checked if `nested` is true
  # By default the generator will search for a folder called `/img` under the site root and process all jpg, png and tiff image files found there.
  img_dir: ["/assets/images"]
  # img_dir: ["/images"]

  # Whether to search in nested directories or not
  nested: false

  # add ".gif" to the format list to generate webp for animated gifs as well
  formats: [".jpeg", ".jpg", ".png", ".tiff"]


  # File extensions for animated gif files
  gifs: [".gif"]

  # Set to true to always regenerate existing webp files
  regenerate: false

  # Local path to the WebP utilities to use (relative or absolute)
  # Omit or leave as nil to use the utilities shipped with the gem, override only to use your local install
  webp_path: nil

  # List of files or directories to exclude
  # e.g. custom or hand generated webp conversion files
  exclude: []

  # append '.webp' to filename after original extension rather than replacing it.
  # Default transforms `image.png` to `image.webp`, while changing to true transforms `image.png` to `image.png.webp`
  append_ext: false
############################################################
comments: false
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

jekyll-minifier:
  exclude: 'atom.xml' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
  preserve_php: true                # Default: false
  remove_spaces_inside_tags: true   # Default: true
  remove_multi_spaces: true         # Default: true
  remove_comments: true             # Default: true
  remove_intertag_spaces: true      # Default: false
  remove_quotes: false              # Default: false
  compress_css: true                # Default: true
  compress_javascript: true         # Default: true
  compress_json: true               # Default: true
  simple_doctype: false             # Default: false
  remove_script_attributes: false   # Default: false
  remove_style_attributes: false    # Default: false
  remove_link_attributes: false     # Default: false
  remove_form_attributes: false     # Default: false
  remove_input_attributes: false    # Default: false
  remove_javascript_protocol: false # Default: false
  remove_http_protocol: false       # Default: false
  remove_https_protocol: false      # Default: false
  preserve_line_breaks: false       # Default: false
  simple_boolean_attributes: false  # Default: false
  compress_js_templates: false      # Default: false
  preserve_patterns:                # Default: (empty)
  uglifier_args:
    harmony: true

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
